### ISSUE TITLE
Should we document in README.md how to build, load, run the application on the Flexy?

### ISSUE THREAD

**Issue by cmo-hms** [HMSAB/flexy-osisoft-connector#2]

**Comment by TomKimsey** [comment]
I dont see any benefit to doing this as it is just following the standard documentation.  I could see including the documentation included with the Flexy java SE toolkit in the repo but then we risk becoming out of sync with the webpage. 

I think the best solution would be do link to here [https://developer.ewon.biz/content/java-0#dev-documents](https://developer.ewon.biz/content/java-0#dev-documents) in the readme.

**Comment by cmo-hms** [comment]
Can we link directly to the document? The link you provided above is the top level page that doesn't have the instructions for loading and configuring the flexy to start the java applet.

**Comment by TomKimsey** [comment]
We could, here is the link to the Java2SE userguide [https://developer.ewon.biz/system/files_force/AUG-072-0-EN-%28JAVA%20J2SE%20Toolkit%20for%20eWON%20Flexy%29.pdf?download=1](https://developer.ewon.biz/system/files_force/AUG-072-0-EN-%28JAVA%20J2SE%20Toolkit%20for%20eWON%20Flexy%29.pdf?download=1)

I always worry about linking directly to files since if they change the filename our link is broken.  Do you think its sufficient to just link to  [https://developer.ewon.biz/content/java-0#dev-documents](https://developer.ewon.biz/content/java-0#dev-documents) and say download the eWON Java Toolkit User guide for J2SE.

**Comment by cmo-hms** [comment]
I'd probably save them the extra searching and clicking and link directly. We can always rev the README.md as soon as we know the link is broken.

**Comment by TomKimsey** [comment]
Link to documentation is added.
